
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 04 19:28:25 CST 2022
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 54;
  public static final int PARENTESIS_CIERRE = 21;
  public static final int CONST = 34;
  public static final int NAMESPACE = 39;
  public static final int CASE = 31;
  public static final int RESTA = 12;
  public static final int INTERFACE = 38;
  public static final int OPERADOR_BOOLEANO = 19;
  public static final int OUT = 41;
  public static final int OPERADOR_CONTEXTUAL = 52;
  public static final int FOR = 9;
  public static final int WRITE = 51;
  public static final int STATIC = 43;
  public static final int IDENTIFICADOR = 53;
  public static final int IGUAL = 10;
  public static final int CORCHETE_CIERRE = 25;
  public static final int OPERADOR_ATRIBUCION = 17;
  public static final int THROW = 45;
  public static final int CLASS = 33;
  public static final int SUMA = 11;
  public static final int MAIN = 26;
  public static final int IF = 5;
  public static final int PUNTO_COMA = 27;
  public static final int ABSTRACT = 29;
  public static final int EOF = 0;
  public static final int SYSTEM = 48;
  public static final int RETURN = 42;
  public static final int CORCHETE_APERTURA = 24;
  public static final int COMILLAS = 2;
  public static final int error = 1;
  public static final int CADENA = 4;
  public static final int TRY = 46;
  public static final int NULL = 40;
  public static final int TIPO_DATO = 3;
  public static final int BREAK = 30;
  public static final int VOID = 47;
  public static final int OPERADOR_LOGICO = 15;
  public static final int OPERADOR_INCREMENTO = 18;
  public static final int FINALLY = 36;
  public static final int ERROR = 28;
  public static final int SWITCH = 44;
  public static final int WRITELINE = 49;
  public static final int OPERADOR_RELACIONAL = 16;
  public static final int ELSE = 6;
  public static final int LLAVE_APERTURA = 22;
  public static final int GOTO = 37;
  public static final int WHILE = 8;
  public static final int DEFAULT = 35;
  public static final int LLAVE_CIERRE = 23;
  public static final int PARENTESIS_APERTURA = 20;
  public static final int DIVISION = 14;
  public static final int CONSOLE = 50;
  public static final int DO = 7;
  public static final int MULTIPLICACION = 13;
  public static final int CATCH = 32;
}

