/* The following code was generated by JFlex 1.6.1 */

/* JFlex example: partial Java language lexer specification */
package lexico;

import jflex.sym;
import java_cup.runtime.*;

/**
 * This class is a simple example lexer.
*/


public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\6\1\4\1\63\2\0\1\63\16\6\4\0\1\4\1\0\1\46"+
    "\1\0\1\5\3\0\1\56\1\57\1\2\1\3\1\61\1\50\1\55"+
    "\1\1\1\7\11\10\1\52\1\60\1\0\1\47\3\0\13\5\1\43"+
    "\1\45\4\5\1\44\4\5\1\42\3\5\1\0\1\62\2\0\1\5"+
    "\1\0\1\11\1\12\1\16\1\25\1\17\1\32\1\33\1\24\1\27"+
    "\1\40\1\22\1\21\1\31\1\26\1\20\1\36\1\5\1\15\1\13"+
    "\1\14\1\30\1\34\1\37\1\35\1\23\1\41\1\53\1\51\1\54"+
    "\1\0\41\6\2\0\4\5\4\0\1\5\2\0\1\6\7\0\1\5"+
    "\4\0\1\5\5\0\27\5\1\0\37\5\1\0\u01ca\5\4\0\14\5"+
    "\16\0\5\5\7\0\1\5\1\0\1\5\21\0\160\6\5\5\1\0"+
    "\2\5\2\0\4\5\1\0\1\5\6\0\1\5\1\0\3\5\1\0"+
    "\1\5\1\0\24\5\1\0\123\5\1\0\213\5\1\0\5\6\2\0"+
    "\246\5\1\0\46\5\2\0\1\5\6\0\51\5\6\0\1\5\1\0"+
    "\55\6\1\0\1\6\1\0\2\6\1\0\2\6\1\0\1\6\10\0"+
    "\33\5\4\0\4\5\15\0\6\6\5\0\1\5\4\0\13\6\1\0"+
    "\1\6\3\0\53\5\37\6\4\0\2\5\1\6\143\5\1\0\1\5"+
    "\10\6\1\0\6\6\2\5\2\6\1\0\4\6\2\5\12\6\3\5"+
    "\2\0\1\5\17\0\1\6\1\5\1\6\36\5\33\6\2\0\131\5"+
    "\13\6\1\5\16\0\12\6\41\5\11\6\2\5\4\0\1\5\2\0"+
    "\1\6\30\5\4\6\1\5\11\6\1\5\3\6\1\5\5\6\22\0"+
    "\31\5\3\6\4\0\13\5\65\0\25\5\1\0\10\5\25\0\61\6"+
    "\66\5\3\6\1\5\22\6\1\5\7\6\12\5\2\6\2\0\12\6"+
    "\1\0\20\5\3\6\1\0\10\5\2\0\2\5\2\0\26\5\1\0"+
    "\7\5\1\0\1\5\3\0\4\5\2\0\1\6\1\5\7\6\2\0"+
    "\2\6\2\0\3\6\1\5\10\0\1\6\4\0\2\5\1\0\3\5"+
    "\2\6\2\0\12\6\4\5\7\0\2\5\1\0\1\6\2\0\3\6"+
    "\1\0\6\5\4\0\2\5\2\0\26\5\1\0\7\5\1\0\2\5"+
    "\1\0\2\5\1\0\2\5\2\0\1\6\1\0\5\6\4\0\2\6"+
    "\2\0\3\6\3\0\1\6\7\0\4\5\1\0\1\5\7\0\14\6"+
    "\3\5\1\6\13\0\3\6\1\0\11\5\1\0\3\5\1\0\26\5"+
    "\1\0\7\5\1\0\2\5\1\0\5\5\2\0\1\6\1\5\10\6"+
    "\1\0\3\6\1\0\3\6\2\0\1\5\17\0\2\5\2\6\2\0"+
    "\12\6\1\0\1\5\7\0\1\5\6\6\1\0\3\6\1\0\10\5"+
    "\2\0\2\5\2\0\26\5\1\0\7\5\1\0\2\5\1\0\5\5"+
    "\2\0\1\6\1\5\7\6\2\0\2\6\2\0\3\6\10\0\2\6"+
    "\4\0\2\5\1\0\3\5\2\6\2\0\12\6\1\0\1\5\20\0"+
    "\1\6\1\5\1\0\6\5\3\0\3\5\1\0\4\5\3\0\2\5"+
    "\1\0\1\5\1\0\2\5\3\0\2\5\3\0\3\5\3\0\14\5"+
    "\4\0\5\6\3\0\3\6\1\0\4\6\2\0\1\5\6\0\1\6"+
    "\16\0\12\6\11\0\1\5\6\0\5\6\10\5\1\0\3\5\1\0"+
    "\27\5\1\0\20\5\3\0\1\5\7\6\1\0\3\6\1\0\4\6"+
    "\7\0\2\6\1\0\3\5\5\0\2\5\2\6\2\0\12\6\20\0"+
    "\1\5\3\6\1\0\10\5\1\0\3\5\1\0\27\5\1\0\12\5"+
    "\1\0\5\5\2\0\1\6\1\5\7\6\1\0\3\6\1\0\4\6"+
    "\7\0\2\6\7\0\1\5\1\0\2\5\2\6\2\0\12\6\1\0"+
    "\2\5\15\0\4\6\1\0\10\5\1\0\3\5\1\0\51\5\2\6"+
    "\1\5\7\6\1\0\3\6\1\0\4\6\1\5\5\0\3\5\1\6"+
    "\7\0\3\5\2\6\2\0\12\6\12\0\6\5\2\0\2\6\1\0"+
    "\22\5\3\0\30\5\1\0\11\5\1\0\1\5\2\0\7\5\3\0"+
    "\1\6\4\0\6\6\1\0\1\6\1\0\10\6\6\0\12\6\2\0"+
    "\2\6\15\0\60\5\1\6\2\5\7\6\4\0\10\5\10\6\1\0"+
    "\12\6\47\0\2\5\1\0\1\5\1\0\5\5\1\0\30\5\1\0"+
    "\1\5\1\0\12\5\1\6\2\5\11\6\1\5\2\0\5\5\1\0"+
    "\1\5\1\0\6\6\2\0\12\6\2\0\4\5\40\0\1\5\27\0"+
    "\2\6\6\0\12\6\13\0\1\6\1\0\1\6\1\0\1\6\4\0"+
    "\2\6\10\5\1\0\44\5\4\0\24\6\1\0\2\6\5\5\13\6"+
    "\1\0\44\6\11\0\1\6\71\0\53\5\24\6\1\5\12\6\6\0"+
    "\6\5\4\6\4\5\3\6\1\5\3\6\2\5\7\6\3\5\4\6"+
    "\15\5\14\6\1\5\17\6\2\0\46\5\1\0\1\5\5\0\1\5"+
    "\2\0\53\5\1\0\u014d\5\1\0\4\5\2\0\7\5\1\0\1\5"+
    "\1\0\4\5\2\0\51\5\1\0\4\5\2\0\41\5\1\0\4\5"+
    "\2\0\7\5\1\0\1\5\1\0\4\5\2\0\17\5\1\0\71\5"+
    "\1\0\4\5\2\0\103\5\2\0\3\6\40\0\20\5\20\0\126\5"+
    "\2\0\6\5\3\0\u026c\5\2\0\21\5\1\0\32\5\5\0\113\5"+
    "\3\0\13\5\7\0\15\5\1\0\4\5\3\6\13\0\22\5\3\6"+
    "\13\0\22\5\2\6\14\0\15\5\1\0\3\5\1\0\2\6\14\0"+
    "\64\5\40\6\3\0\1\5\3\0\2\5\1\6\2\0\12\6\41\0"+
    "\4\6\1\0\12\6\6\0\131\5\7\0\5\5\2\6\42\5\1\6"+
    "\1\5\5\0\106\5\12\0\37\5\1\0\14\6\4\0\14\6\12\0"+
    "\12\6\36\5\2\0\5\5\13\0\54\5\4\0\32\5\6\0\12\6"+
    "\46\0\27\5\5\6\4\0\65\5\12\6\1\0\35\6\2\0\13\6"+
    "\6\0\12\6\15\0\1\5\10\0\16\6\102\0\5\6\57\5\21\6"+
    "\7\5\4\0\12\6\21\0\11\6\14\0\3\6\36\5\15\6\2\5"+
    "\12\6\54\5\16\6\14\0\44\5\24\6\10\0\12\6\3\0\3\5"+
    "\12\6\44\5\2\0\11\5\7\0\53\5\2\0\3\5\20\0\3\6"+
    "\1\0\25\6\4\5\1\6\6\5\1\6\2\5\3\6\1\5\5\0"+
    "\300\5\72\6\1\0\5\6\u0116\5\2\0\6\5\2\0\46\5\2\0"+
    "\6\5\2\0\10\5\1\0\1\5\1\0\1\5\1\0\1\5\1\0"+
    "\37\5\2\0\65\5\1\0\7\5\1\0\1\5\3\0\3\5\1\0"+
    "\7\5\3\0\4\5\2\0\6\5\4\0\15\5\5\0\3\5\1\0"+
    "\7\5\16\0\5\6\32\0\5\6\20\0\2\5\23\0\1\5\13\0"+
    "\5\6\1\0\12\6\1\0\1\5\15\0\1\5\20\0\15\5\3\0"+
    "\40\5\20\0\15\6\4\0\1\6\3\0\14\6\21\0\1\5\4\0"+
    "\1\5\2\0\12\5\1\0\1\5\3\0\5\5\6\0\1\5\1\0"+
    "\1\5\1\0\1\5\1\0\4\5\1\0\13\5\2\0\4\5\5\0"+
    "\5\5\4\0\1\5\21\0\51\5\u0a77\0\57\5\1\0\57\5\1\0"+
    "\205\5\6\0\4\5\3\6\2\5\14\0\46\5\1\0\1\5\5\0"+
    "\1\5\2\0\70\5\7\0\1\5\17\0\1\6\27\5\11\0\7\5"+
    "\1\0\7\5\1\0\7\5\1\0\7\5\1\0\7\5\1\0\7\5"+
    "\1\0\7\5\1\0\7\5\1\0\40\6\57\0\1\5\u01d5\0\3\5"+
    "\31\0\11\5\6\6\1\0\5\5\2\0\5\5\4\0\126\5\2\0"+
    "\2\6\2\0\3\5\1\0\132\5\1\0\4\5\5\0\53\5\1\0"+
    "\136\5\21\0\33\5\65\0\20\5\u0200\0\u19b6\5\112\0\u51f0\5\20\0"+
    "\u048d\5\103\0\56\5\2\0\u010d\5\3\0\20\5\12\6\2\5\24\0"+
    "\57\5\1\6\4\0\12\6\1\0\37\5\2\6\120\5\2\6\45\0"+
    "\11\5\2\0\147\5\2\0\65\5\2\0\5\5\60\0\13\5\1\6"+
    "\3\5\1\6\4\5\1\6\27\5\5\6\20\0\1\5\7\0\64\5"+
    "\14\0\2\6\62\5\22\6\12\0\12\6\6\0\22\6\6\5\3\0"+
    "\1\5\1\0\2\5\13\6\34\5\10\6\2\0\27\5\15\6\14\0"+
    "\35\5\3\0\4\6\57\5\16\6\16\0\1\5\12\6\6\0\5\5"+
    "\1\6\12\5\12\6\5\5\1\0\51\5\16\6\11\0\3\5\1\6"+
    "\10\5\2\6\2\0\12\6\6\0\27\5\3\0\1\5\3\6\62\5"+
    "\1\6\1\5\3\6\2\5\2\6\5\5\2\6\1\5\1\6\1\5"+
    "\30\0\3\5\2\0\13\5\5\6\2\0\3\5\2\6\12\0\6\5"+
    "\2\0\6\5\2\0\6\5\11\0\7\5\1\0\7\5\1\0\53\5"+
    "\1\0\14\5\10\0\163\5\10\6\1\0\2\6\2\0\12\6\6\0"+
    "\u2ba4\5\14\0\27\5\4\0\61\5\u2104\0\u016e\5\2\0\152\5\46\0"+
    "\7\5\14\0\5\5\5\0\1\5\1\6\12\5\1\0\15\5\1\0"+
    "\5\5\1\0\1\5\1\0\2\5\1\0\2\5\1\0\154\5\41\0"+
    "\u016b\5\22\0\100\5\2\0\66\5\50\0\15\5\3\0\20\6\20\0"+
    "\20\6\3\0\2\5\30\0\3\5\31\0\1\5\6\0\5\5\1\0"+
    "\207\5\2\0\1\6\4\0\1\5\13\0\12\6\7\0\32\5\4\0"+
    "\1\5\1\0\32\5\13\0\131\5\3\0\6\5\2\0\6\5\2\0"+
    "\6\5\2\0\3\5\3\0\2\5\3\0\2\5\22\0\3\6\4\0"+
    "\14\5\1\0\32\5\1\0\23\5\1\0\2\5\1\0\17\5\2\0"+
    "\16\5\42\0\173\5\105\0\65\5\210\0\1\6\202\0\35\5\3\0"+
    "\61\5\17\0\1\6\37\0\40\5\15\0\36\5\5\0\46\5\5\6"+
    "\5\0\36\5\2\0\44\5\4\0\10\5\1\0\5\5\52\0\236\5"+
    "\2\0\12\6\6\0\44\5\4\0\44\5\4\0\50\5\10\0\64\5"+
    "\234\0\u0137\5\11\0\26\5\12\0\10\5\230\0\6\5\2\0\1\5"+
    "\1\0\54\5\1\0\2\5\3\0\1\5\2\0\27\5\12\0\27\5"+
    "\11\0\37\5\101\0\23\5\1\0\2\5\12\0\26\5\12\0\32\5"+
    "\106\0\70\5\6\0\2\5\100\0\1\5\3\6\1\0\2\6\5\0"+
    "\4\6\4\5\1\0\3\5\1\0\35\5\2\0\3\6\4\0\1\6"+
    "\40\0\35\5\3\0\35\5\43\0\10\5\1\0\34\5\2\6\31\0"+
    "\66\5\12\0\26\5\12\0\23\5\15\0\22\5\156\0\111\5\67\0"+
    "\63\5\15\0\63\5\15\0\44\5\4\6\10\0\12\6\u01c6\0\35\5"+
    "\12\0\1\5\10\0\26\5\13\6\217\0\27\5\11\0\3\6\65\5"+
    "\17\6\37\0\12\6\17\0\4\6\55\5\13\6\2\0\1\6\17\0"+
    "\1\6\2\0\31\5\7\0\12\6\6\0\3\6\44\5\16\6\1\0"+
    "\12\6\4\0\1\5\2\6\11\0\43\5\1\6\2\0\1\5\11\0"+
    "\3\6\60\5\16\6\4\5\4\0\4\6\3\0\12\6\1\5\1\0"+
    "\1\5\43\0\22\5\1\0\31\5\14\6\6\0\1\6\101\0\7\5"+
    "\1\0\1\5\1\0\4\5\1\0\17\5\1\0\12\5\7\0\57\5"+
    "\14\6\5\0\12\6\6\0\4\6\1\0\10\5\2\0\2\5\2\0"+
    "\26\5\1\0\7\5\1\0\2\5\1\0\5\5\1\0\2\6\1\5"+
    "\7\6\2\0\2\6\2\0\3\6\2\0\1\5\6\0\1\6\5\0"+
    "\5\5\2\6\2\0\7\6\3\0\5\6\213\0\65\5\22\6\4\5"+
    "\5\0\12\6\4\0\1\6\1\5\40\0\60\5\24\6\2\5\1\0"+
    "\1\5\10\0\12\6\246\0\57\5\7\6\2\0\11\6\27\0\4\5"+
    "\2\6\42\0\60\5\21\6\3\0\1\5\13\0\12\6\46\0\53\5"+
    "\15\6\1\5\7\0\12\6\66\0\33\5\2\0\17\6\4\0\12\6"+
    "\306\0\54\5\17\6\145\0\100\5\12\6\25\0\1\5\240\0\10\5"+
    "\2\0\47\5\7\6\2\0\7\6\1\5\1\0\1\5\1\6\33\0"+
    "\1\5\12\6\50\5\7\6\1\5\4\6\10\0\1\6\10\0\1\5"+
    "\13\6\56\5\20\6\3\0\1\5\42\0\71\5\u0107\0\11\5\1\0"+
    "\45\5\10\6\1\0\10\6\1\5\17\0\12\6\30\0\36\5\2\0"+
    "\26\6\1\0\16\6\111\0\7\5\1\0\2\5\1\0\46\5\6\6"+
    "\3\0\1\6\1\0\2\6\1\0\7\6\1\5\1\6\10\0\12\6"+
    "\6\0\6\5\1\0\2\5\1\0\40\5\5\6\1\0\2\6\1\0"+
    "\5\6\1\5\7\0\12\6\u0136\0\23\5\4\6\346\0\4\5\37\0"+
    "\u039a\5\146\0\157\5\21\0\304\5\u0abc\0\u042f\5\1\0\11\6\u0fc7\0"+
    "\u0247\5\u21b9\0\u0239\5\7\0\37\5\1\0\12\6\146\0\36\5\2\0"+
    "\5\6\13\0\60\5\7\6\11\0\4\5\14\0\12\6\11\0\25\5"+
    "\5\0\23\5\u02b0\0\100\5\200\0\113\5\4\0\1\6\1\5\67\6"+
    "\7\0\4\6\15\5\100\0\2\5\1\0\1\5\34\0\u17f8\5\10\0"+
    "\u02f3\5\u250d\0\u011f\5\61\0\3\5\21\0\4\5\10\0\u018c\5\u0904\0"+
    "\153\5\5\0\15\5\3\0\11\5\7\0\12\5\3\0\2\6\1\0"+
    "\4\6\u14c1\0\5\6\3\0\26\6\2\0\7\6\36\0\4\6\224\0"+
    "\3\6\u01bb\0\125\5\1\0\107\5\1\0\2\5\2\0\1\5\2\0"+
    "\2\5\2\0\4\5\1\0\14\5\1\0\1\5\1\0\7\5\1\0"+
    "\101\5\1\0\4\5\2\0\10\5\1\0\7\5\1\0\34\5\1\0"+
    "\4\5\1\0\5\5\1\0\1\5\3\0\7\5\1\0\u0154\5\2\0"+
    "\31\5\1\0\31\5\1\0\37\5\1\0\31\5\1\0\37\5\1\0"+
    "\31\5\1\0\37\5\1\0\31\5\1\0\37\5\1\0\31\5\1\0"+
    "\10\5\2\0\62\6\u0200\0\67\6\4\0\62\6\10\0\1\6\16\0"+
    "\1\6\26\0\5\6\1\0\17\6\u0550\0\7\6\1\0\21\6\2\0"+
    "\7\6\1\0\2\6\1\0\5\6\325\0\55\5\3\0\7\6\7\5"+
    "\2\0\12\6\4\0\1\5\u0171\0\54\5\16\6\5\0\1\5\u0500\0"+
    "\305\5\13\0\7\6\51\0\104\5\7\6\1\5\4\0\12\6\u0356\0"+
    "\1\5\u014f\0\4\5\1\0\33\5\1\0\2\5\1\0\1\5\2\0"+
    "\1\5\1\0\12\5\1\0\4\5\1\0\1\5\1\0\1\5\6\0"+
    "\1\5\4\0\1\5\1\0\1\5\1\0\1\5\1\0\3\5\1\0"+
    "\2\5\1\0\1\5\2\0\1\5\1\0\1\5\1\0\1\5\1\0"+
    "\1\5\1\0\1\5\1\0\2\5\1\0\1\5\2\0\4\5\1\0"+
    "\7\5\1\0\4\5\1\0\4\5\1\0\1\5\1\0\12\5\1\0"+
    "\21\5\5\0\3\5\1\0\5\5\1\0\21\5\u1144\0\ua6d7\5\51\0"+
    "\u1035\5\13\0\336\5\2\0\u1682\5\16\0\u1d31\5\u0c1f\0\u021e\5\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\6\36\0\140\6\200\0\360\6\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\2\7"+
    "\25\6\1\10\1\11\1\12\1\1\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\0"+
    "\1\25\2\0\1\6\1\26\35\6\1\27\3\6\1\30"+
    "\1\31\1\6\1\32\22\6\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\2\25\1\41\15\6\1\42\6\6\1\43"+
    "\14\6\1\44\11\6\1\45\1\6\1\46\10\6\1\47"+
    "\17\6\1\50\1\51\1\6\1\52\1\53\11\6\1\54"+
    "\2\6\1\55\2\6\1\56\4\6\1\57\1\6\1\60"+
    "\1\61\6\6\1\62\1\63\5\6\1\64\7\6\1\65"+
    "\5\6\1\66\1\67\10\6\1\70\1\6\1\71\1\72"+
    "\5\6\1\73\3\6\1\74\2\6\1\75\1\76\1\6"+
    "\1\77\1\6\1\100\15\6\1\101\1\102\2\6\1\103"+
    "\1\6\1\104\1\6\1\105\5\6\1\106\3\6\1\107"+
    "\1\6\1\110\1\111\1\112\1\113\1\114\1\115\1\6"+
    "\1\116\2\6\1\117\1\6\1\120\5\6\1\121\4\6"+
    "\1\122\1\123\4\6\1\124\2\6\1\125\6\6\1\126"+
    "\3\6\1\127\1\6\1\130\5\6\1\131\1\132\1\133"+
    "\1\6\1\134\2\6\1\135\1\6\1\136\1\137\1\140"+
    "\1\141\1\142\1\143\1\6\1\144\1\6\1\145\3\6"+
    "\1\146\1\6\1\147\1\150\1\151\1\152\1\153\1\154";

  private static int [] zzUnpackAction() {
    int [] result = new int[387];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\150\0\150\0\150\0\320"+
    "\0\150\0\u0104\0\u0138\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c"+
    "\0\u0270\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc"+
    "\0\u0410\0\u0444\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\150"+
    "\0\u057c\0\150\0\u05b0\0\150\0\150\0\150\0\150\0\150"+
    "\0\150\0\150\0\u05e4\0\150\0\u0618\0\u064c\0\u064c\0\u0680"+
    "\0\u06b4\0\u06e8\0\320\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec"+
    "\0\u0820\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c"+
    "\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c"+
    "\0\u0b60\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc"+
    "\0\u0d00\0\u0d34\0\u0d68\0\u0d9c\0\320\0\u0dd0\0\u0e04\0\320"+
    "\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4"+
    "\0\u0fd8\0\u100c\0\u1040\0\u1074\0\u10a8\0\u10dc\0\u1110\0\u1144"+
    "\0\u1178\0\u11ac\0\150\0\150\0\150\0\150\0\150\0\150"+
    "\0\150\0\u11e0\0\150\0\u1214\0\u1248\0\u127c\0\u12b0\0\u12e4"+
    "\0\u1318\0\u134c\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u1450\0\u1484"+
    "\0\320\0\u14b8\0\u14ec\0\u1520\0\u1554\0\u1588\0\u15bc\0\320"+
    "\0\u15f0\0\u1624\0\u1658\0\u168c\0\u16c0\0\u16f4\0\u1728\0\u175c"+
    "\0\u1790\0\u17c4\0\u17f8\0\u182c\0\320\0\u1860\0\u1894\0\u18c8"+
    "\0\u18fc\0\u1930\0\u1964\0\u1998\0\u19cc\0\u1a00\0\320\0\u1a34"+
    "\0\u1a68\0\u1a9c\0\u1ad0\0\u1b04\0\u1b38\0\u1b6c\0\u1ba0\0\u1bd4"+
    "\0\u1c08\0\u1c3c\0\u1c70\0\u1ca4\0\u1cd8\0\u1d0c\0\u1d40\0\u1d74"+
    "\0\u1da8\0\u1ddc\0\u1e10\0\u1e44\0\u1e78\0\u1eac\0\u1ee0\0\u1f14"+
    "\0\u1f48\0\320\0\320\0\u1f7c\0\320\0\320\0\u1fb0\0\u1fe4"+
    "\0\u2018\0\u204c\0\u2080\0\u20b4\0\u20e8\0\u211c\0\u2150\0\320"+
    "\0\u2184\0\u21b8\0\320\0\u21ec\0\u2220\0\320\0\u2254\0\u2288"+
    "\0\u22bc\0\u22f0\0\320\0\u2324\0\320\0\320\0\u2358\0\u238c"+
    "\0\u23c0\0\u23f4\0\u2428\0\u245c\0\320\0\320\0\u2490\0\u24c4"+
    "\0\u24f8\0\u252c\0\u2560\0\320\0\u2594\0\u25c8\0\u25fc\0\u2630"+
    "\0\u2664\0\u2698\0\u26cc\0\320\0\u2700\0\u2734\0\u2768\0\u279c"+
    "\0\u27d0\0\320\0\320\0\u2804\0\u2838\0\u286c\0\u28a0\0\u28d4"+
    "\0\u2908\0\u293c\0\u2970\0\320\0\u29a4\0\320\0\320\0\u29d8"+
    "\0\u2a0c\0\u2a40\0\u2a74\0\u2aa8\0\320\0\u2adc\0\u2b10\0\u2b44"+
    "\0\320\0\u2b78\0\u2bac\0\320\0\320\0\u2be0\0\320\0\u2c14"+
    "\0\320\0\u2c48\0\u2c7c\0\u2cb0\0\u2ce4\0\u2d18\0\u2d4c\0\u2d80"+
    "\0\u2db4\0\u2de8\0\u2e1c\0\u2e50\0\u2e84\0\u2eb8\0\320\0\320"+
    "\0\u2eec\0\u2f20\0\320\0\u2f54\0\320\0\u2f88\0\320\0\u2fbc"+
    "\0\u2ff0\0\u3024\0\u3058\0\u308c\0\320\0\u30c0\0\u30f4\0\u3128"+
    "\0\320\0\u315c\0\320\0\320\0\320\0\320\0\320\0\320"+
    "\0\u3190\0\320\0\u31c4\0\u31f8\0\320\0\u322c\0\320\0\u3260"+
    "\0\u3294\0\u32c8\0\u32fc\0\u3330\0\320\0\u3364\0\u3398\0\u33cc"+
    "\0\u3400\0\320\0\320\0\u3434\0\u3468\0\u349c\0\u34d0\0\320"+
    "\0\u3504\0\u3538\0\320\0\u356c\0\u35a0\0\u35d4\0\u3608\0\u363c"+
    "\0\u3670\0\320\0\u36a4\0\u36d8\0\u370c\0\320\0\u3740\0\320"+
    "\0\u3774\0\u37a8\0\u37dc\0\u3810\0\u3844\0\320\0\320\0\320"+
    "\0\u3878\0\320\0\u38ac\0\u38e0\0\320\0\u3914\0\320\0\320"+
    "\0\320\0\320\0\320\0\320\0\u3948\0\320\0\u397c\0\320"+
    "\0\u39b0\0\u39e4\0\u3a18\0\320\0\u3a4c\0\320\0\320\0\320"+
    "\0\320\0\320\0\320";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[387];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\3\10\1\24\1\25\1\26\1\27\1\10"+
    "\1\30\1\31\1\32\1\10\1\33\1\34\2\10\1\35"+
    "\1\10\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\3\1\52\1\3"+
    "\1\7\46\53\1\54\13\53\1\55\1\3\64\0\1\56"+
    "\1\57\1\60\55\56\1\61\3\56\5\0\41\10\25\0"+
    "\2\12\60\0\5\10\1\62\1\63\1\10\1\64\30\10"+
    "\23\0\4\10\1\65\3\10\1\66\2\10\1\67\2\10"+
    "\1\70\22\10\23\0\5\10\1\71\1\10\1\72\2\10"+
    "\1\73\4\10\1\74\2\10\1\75\7\10\1\76\6\10"+
    "\23\0\10\10\1\77\5\10\1\100\1\101\21\10\23\0"+
    "\12\10\1\102\26\10\23\0\4\10\1\103\6\10\1\104"+
    "\1\105\2\10\1\106\21\10\23\0\14\10\1\107\4\10"+
    "\1\110\5\10\1\111\1\112\10\10\23\0\5\10\1\113"+
    "\15\10\1\114\3\10\1\115\1\10\1\116\7\10\23\0"+
    "\13\10\1\117\25\10\23\0\12\10\1\120\1\121\25\10"+
    "\23\0\4\10\1\122\5\10\1\123\10\10\1\124\15\10"+
    "\23\0\6\10\1\125\12\10\1\126\2\10\1\127\1\130"+
    "\13\10\23\0\6\10\1\131\5\10\1\132\4\10\1\133"+
    "\1\134\16\10\23\0\4\10\1\135\6\10\1\136\1\137"+
    "\5\10\1\140\16\10\23\0\13\10\1\141\25\10\23\0"+
    "\13\10\1\142\6\10\1\143\16\10\23\0\4\10\1\144"+
    "\3\10\1\145\12\10\1\146\15\10\23\0\17\10\1\147"+
    "\21\10\23\0\10\10\1\150\30\10\23\0\12\10\1\151"+
    "\26\10\23\0\4\10\1\152\34\10\65\0\1\153\65\0"+
    "\1\154\12\0\46\53\1\0\13\53\16\0\1\155\1\156"+
    "\10\0\1\157\17\0\1\160\15\0\1\56\1\161\63\56"+
    "\1\162\63\56\1\163\62\56\5\0\6\10\1\164\32\10"+
    "\23\0\26\10\1\165\12\10\23\0\6\10\1\166\32\10"+
    "\23\0\12\10\1\167\26\10\23\0\13\10\1\170\25\10"+
    "\23\0\7\10\1\171\31\10\23\0\16\10\1\172\22\10"+
    "\23\0\4\10\1\173\3\10\1\174\30\10\23\0\4\10"+
    "\1\175\34\10\23\0\13\10\1\176\25\10\23\0\34\10"+
    "\1\177\4\10\23\0\22\10\1\200\16\10\23\0\16\10"+
    "\1\201\4\10\1\202\15\10\23\0\31\10\1\203\7\10"+
    "\23\0\10\10\1\204\11\10\1\205\16\10\23\0\4\10"+
    "\1\206\2\10\1\207\15\10\1\210\13\10\23\0\6\10"+
    "\1\211\1\212\31\10\23\0\21\10\1\213\17\10\23\0"+
    "\4\10\1\214\34\10\23\0\4\10\1\215\5\10\1\216"+
    "\26\10\23\0\6\10\1\217\32\10\23\0\23\10\1\220"+
    "\15\10\23\0\12\10\1\221\26\10\23\0\7\10\1\222"+
    "\21\10\1\223\7\10\23\0\33\10\1\224\5\10\23\0"+
    "\7\10\1\225\31\10\23\0\12\10\1\226\26\10\23\0"+
    "\12\10\1\227\26\10\23\0\11\10\1\230\7\10\1\231"+
    "\17\10\23\0\11\10\1\232\2\10\1\233\10\10\1\234"+
    "\13\10\23\0\23\10\1\235\15\10\23\0\24\10\1\236"+
    "\14\10\23\0\32\10\1\237\6\10\23\0\14\10\1\240"+
    "\24\10\23\0\7\10\1\241\31\10\23\0\31\10\1\242"+
    "\7\10\23\0\17\10\1\243\2\10\1\244\16\10\23\0"+
    "\13\10\1\245\25\10\23\0\6\10\1\246\2\10\1\247"+
    "\27\10\23\0\21\10\1\250\17\10\23\0\14\10\1\251"+
    "\24\10\23\0\10\10\1\252\30\10\23\0\13\10\1\253"+
    "\25\10\23\0\21\10\1\254\6\10\1\255\10\10\23\0"+
    "\7\10\1\256\31\10\23\0\22\10\1\257\16\10\23\0"+
    "\10\10\1\260\30\10\23\0\10\10\1\261\30\10\23\0"+
    "\13\10\1\262\6\10\1\263\16\10\23\0\5\10\1\264"+
    "\33\10\23\0\22\10\1\265\16\10\23\0\22\10\1\266"+
    "\16\10\23\0\4\10\1\267\34\10\23\0\22\10\1\270"+
    "\16\10\17\0\1\161\67\0\7\10\1\271\31\10\23\0"+
    "\6\10\1\272\32\10\23\0\12\10\1\273\26\10\23\0"+
    "\4\10\1\274\34\10\23\0\14\10\1\275\24\10\23\0"+
    "\12\10\1\276\26\10\23\0\7\10\1\277\31\10\23\0"+
    "\7\10\1\300\1\10\1\301\27\10\23\0\22\10\1\302"+
    "\1\303\15\10\23\0\14\10\1\304\24\10\23\0\10\10"+
    "\1\305\30\10\23\0\12\10\1\306\26\10\23\0\7\10"+
    "\1\307\31\10\23\0\12\10\1\310\26\10\23\0\12\10"+
    "\1\311\26\10\23\0\13\10\1\312\25\10\23\0\6\10"+
    "\1\313\32\10\23\0\20\10\1\314\20\10\23\0\23\10"+
    "\1\315\15\10\23\0\12\10\1\316\26\10\23\0\11\10"+
    "\1\317\27\10\23\0\6\10\1\320\1\321\31\10\23\0"+
    "\6\10\1\322\32\10\23\0\10\10\1\323\30\10\23\0"+
    "\11\10\1\324\27\10\23\0\12\10\1\325\26\10\23\0"+
    "\24\10\1\326\14\10\23\0\21\10\1\327\17\10\23\0"+
    "\12\10\1\330\26\10\23\0\14\10\1\331\24\10\23\0"+
    "\12\10\1\332\26\10\23\0\10\10\1\333\30\10\23\0"+
    "\10\10\1\334\30\10\23\0\15\10\1\335\23\10\23\0"+
    "\26\10\1\336\12\10\23\0\22\10\1\337\16\10\23\0"+
    "\12\10\1\340\26\10\23\0\4\10\1\341\34\10\23\0"+
    "\5\10\1\342\33\10\23\0\12\10\1\343\26\10\23\0"+
    "\14\10\1\344\24\10\23\0\12\10\1\345\26\10\23\0"+
    "\14\10\1\346\24\10\23\0\13\10\1\347\25\10\23\0"+
    "\21\10\1\350\17\10\23\0\21\10\1\351\17\10\23\0"+
    "\4\10\1\352\34\10\23\0\17\10\1\353\21\10\23\0"+
    "\7\10\1\354\31\10\23\0\6\10\1\355\32\10\23\0"+
    "\12\10\1\356\26\10\23\0\4\10\1\357\34\10\23\0"+
    "\4\10\1\360\34\10\23\0\12\10\1\361\26\10\23\0"+
    "\13\10\1\362\25\10\23\0\20\10\1\363\20\10\23\0"+
    "\7\10\1\364\31\10\23\0\4\10\1\365\34\10\23\0"+
    "\7\10\1\366\31\10\23\0\27\10\1\367\11\10\23\0"+
    "\14\10\1\370\24\10\23\0\14\10\1\371\24\10\23\0"+
    "\7\10\1\372\31\10\23\0\20\10\1\373\20\10\23\0"+
    "\21\10\1\374\17\10\23\0\10\10\1\375\30\10\23\0"+
    "\15\10\1\376\23\10\23\0\12\10\1\377\26\10\23\0"+
    "\22\10\1\u0100\16\10\23\0\15\10\1\u0101\23\10\23\0"+
    "\21\10\1\u0102\17\10\23\0\11\10\1\u0103\27\10\23\0"+
    "\12\10\1\u0104\26\10\23\0\7\10\1\u0105\31\10\23\0"+
    "\13\10\1\u0106\25\10\23\0\11\10\1\u0107\27\10\23\0"+
    "\13\10\1\u0108\25\10\23\0\32\10\1\u0109\6\10\23\0"+
    "\13\10\1\u010a\25\10\23\0\10\10\1\u010b\30\10\23\0"+
    "\17\10\1\u010c\21\10\23\0\7\10\1\u010d\31\10\23\0"+
    "\22\10\1\u010e\16\10\23\0\6\10\1\u010f\32\10\23\0"+
    "\15\10\1\u0110\23\10\23\0\7\10\1\u0111\31\10\23\0"+
    "\10\10\1\u0112\30\10\23\0\22\10\1\u0113\16\10\23\0"+
    "\11\10\1\u0114\27\10\23\0\10\10\1\u0115\30\10\23\0"+
    "\4\10\1\u0116\34\10\23\0\24\10\1\u0117\14\10\23\0"+
    "\26\10\1\u0118\12\10\23\0\23\10\1\u0119\15\10\23\0"+
    "\14\10\1\u011a\24\10\23\0\6\10\1\u011b\32\10\23\0"+
    "\10\10\1\u011c\30\10\23\0\22\10\1\u011d\16\10\23\0"+
    "\10\10\1\u011e\30\10\23\0\26\10\1\u011f\12\10\23\0"+
    "\26\10\1\u0120\12\10\23\0\25\10\1\u0121\13\10\23\0"+
    "\12\10\1\u0122\26\10\23\0\12\10\1\u0123\26\10\23\0"+
    "\4\10\1\u0124\34\10\23\0\7\10\1\u0125\31\10\23\0"+
    "\14\10\1\u0126\24\10\23\0\20\10\1\u0127\20\10\23\0"+
    "\23\10\1\u0128\15\10\23\0\24\10\1\u0129\14\10\23\0"+
    "\12\10\1\u012a\26\10\23\0\4\10\1\u012b\34\10\23\0"+
    "\22\10\1\u012c\16\10\23\0\12\10\1\u012d\26\10\23\0"+
    "\12\10\1\u012e\26\10\23\0\36\10\1\u012f\2\10\23\0"+
    "\4\10\1\u0130\34\10\23\0\11\10\1\u0131\27\10\23\0"+
    "\4\10\1\u0132\34\10\23\0\26\10\1\u0133\12\10\23\0"+
    "\7\10\1\u0134\31\10\23\0\20\10\1\u0135\20\10\23\0"+
    "\25\10\1\u0136\13\10\23\0\17\10\1\u0137\21\10\23\0"+
    "\25\10\1\u0138\13\10\23\0\21\10\1\u0139\17\10\23\0"+
    "\21\10\1\u013a\17\10\23\0\21\10\1\u013b\17\10\23\0"+
    "\12\10\1\u013c\26\10\23\0\21\10\1\u013d\17\10\23\0"+
    "\11\10\1\u013e\27\10\23\0\7\10\1\u013f\31\10\23\0"+
    "\22\10\1\u0140\16\10\23\0\7\10\1\u0141\31\10\23\0"+
    "\4\10\1\u0142\34\10\23\0\4\10\1\u0143\34\10\23\0"+
    "\14\10\1\u0144\24\10\23\0\12\10\1\u0145\26\10\23\0"+
    "\31\10\1\u0146\7\10\23\0\21\10\1\u0147\3\10\1\u0148"+
    "\13\10\23\0\11\10\1\u0149\27\10\23\0\7\10\1\u014a"+
    "\31\10\23\0\12\10\1\u014b\26\10\23\0\11\10\1\u014c"+
    "\27\10\23\0\11\10\1\u014d\27\10\23\0\14\10\1\u014e"+
    "\24\10\23\0\4\10\1\u014f\34\10\23\0\6\10\1\u0150"+
    "\32\10\23\0\11\10\1\u0151\27\10\23\0\7\10\1\u0152"+
    "\31\10\23\0\11\10\1\u0153\27\10\23\0\36\10\1\u0154"+
    "\2\10\23\0\22\10\1\u0155\16\10\23\0\11\10\1\u0156"+
    "\27\10\23\0\14\10\1\u0157\24\10\23\0\14\10\1\u0158"+
    "\24\10\23\0\23\10\1\u0159\15\10\23\0\20\10\1\u015a"+
    "\20\10\23\0\22\10\1\u015b\16\10\23\0\20\10\1\u015c"+
    "\20\10\23\0\13\10\1\u015d\25\10\23\0\14\10\1\u015e"+
    "\24\10\23\0\7\10\1\u015f\31\10\23\0\7\10\1\u0160"+
    "\31\10\23\0\4\10\1\u0161\34\10\23\0\4\10\1\u0162"+
    "\34\10\23\0\4\10\1\u0163\34\10\23\0\22\10\1\u0164"+
    "\16\10\23\0\15\10\1\u0165\23\10\23\0\17\10\1\u0166"+
    "\21\10\23\0\16\10\1\u0167\22\10\23\0\14\10\1\u0168"+
    "\24\10\23\0\7\10\1\u0169\31\10\23\0\12\10\1\u016a"+
    "\26\10\23\0\22\10\1\u016b\16\10\23\0\21\10\1\u016c"+
    "\17\10\23\0\7\10\1\u016d\31\10\23\0\14\10\1\u016e"+
    "\24\10\23\0\16\10\1\u016f\22\10\23\0\12\10\1\u0170"+
    "\26\10\23\0\7\10\1\u0171\31\10\23\0\12\10\1\u0172"+
    "\26\10\23\0\10\10\1\u0173\30\10\23\0\12\10\1\u0174"+
    "\26\10\23\0\11\10\1\u0175\27\10\23\0\14\10\1\u0176"+
    "\24\10\23\0\11\10\1\u0177\27\10\23\0\7\10\1\u0178"+
    "\31\10\23\0\12\10\1\u0179\26\10\23\0\12\10\1\u017a"+
    "\26\10\23\0\21\10\1\u017b\17\10\23\0\12\10\1\u017c"+
    "\26\10\23\0\13\10\1\u017d\25\10\23\0\12\10\1\u017e"+
    "\26\10\23\0\12\10\1\u017f\26\10\23\0\20\10\1\u0180"+
    "\20\10\23\0\20\10\1\u0181\20\10\23\0\12\10\1\u0182"+
    "\26\10\23\0\11\10\1\u0183\27\10\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14976];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\3\11\1\1\1\11\26\1\1\11"+
    "\1\1\1\11\1\1\7\11\1\1\1\11\1\1\1\0"+
    "\1\1\2\0\71\1\7\11\1\1\1\11\u0110\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[387];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer string = new StringBuffer();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
      
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3598) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character --**"+
                                                        yytext()+"**--");
            }
          case 109: break;
          case 2: 
            { return symbol(Operators.DIVISION.value,yytext());
            }
          case 110: break;
          case 3: 
            { return symbol(Operators.MULTIPLICATION.value,yytext());
            }
          case 111: break;
          case 4: 
            { return symbol(Operators.PLUS.value,yytext());
            }
          case 112: break;
          case 5: 
            { return symbol(Operators.WHITESPACE.value,yytext());
            }
          case 113: break;
          case 6: 
            { return symbol(Operators.IDENTIFIER.value,yytext());
            }
          case 114: break;
          case 7: 
            { return symbol(ReservedWords.INTEGER_LITERAL.value,yytext());
            }
          case 115: break;
          case 8: 
            { string.setLength(0); yybegin(STRING);
            }
          case 116: break;
          case 9: 
            { return symbol(Operators.EQ.value,yytext());
            }
          case 117: break;
          case 10: 
            { return symbol(Operators.SUBTRACTION.value,yytext());
            }
          case 118: break;
          case 11: 
            { return symbol(Operators.TERN_OR.value,yytext());
            }
          case 119: break;
          case 12: 
            { return symbol(Operators.OPEN_BRACKET.value,yytext());
            }
          case 120: break;
          case 13: 
            { return symbol(Operators.CLOSE_BRACKET.value,yytext());
            }
          case 121: break;
          case 14: 
            { return symbol(Operators.DOTE.value,yytext());
            }
          case 122: break;
          case 15: 
            { return symbol(Operators.OPEN_PARENTHESES.value,yytext());
            }
          case 123: break;
          case 16: 
            { return symbol(Operators.CLOSE_PARENTHESES.value,yytext());
            }
          case 124: break;
          case 17: 
            { return symbol(Operators.COMMA.value,yytext());
            }
          case 125: break;
          case 18: 
            { string.append( yytext() );
            }
          case 126: break;
          case 19: 
            { yybegin(YYINITIAL); 
                                       return symbol(ReservedWords.STRING_LITERAL.value, 
                                       string.toString());
            }
          case 127: break;
          case 20: 
            { string.append('\\');
            }
          case 128: break;
          case 21: 
            { return symbol(Operators.COMMENT.value,yytext());
            }
          case 129: break;
          case 22: 
            { return symbol(ReservedWords.AS.value,yytext());
            }
          case 130: break;
          case 23: 
            { return symbol(ReservedWords.DO.value,yytext());
            }
          case 131: break;
          case 24: 
            { return symbol(ReservedWords.IS.value,yytext());
            }
          case 132: break;
          case 25: 
            { return symbol(ReservedWords.IN.value,yytext());
            }
          case 133: break;
          case 26: 
            { return symbol(ReservedWords.IF.value,yytext());
            }
          case 134: break;
          case 27: 
            { return symbol(Operators.EQEQ.value,yytext());
            }
          case 135: break;
          case 28: 
            { return symbol(Operators.OR.value,yytext());
            }
          case 136: break;
          case 29: 
            { string.append('\t');
            }
          case 137: break;
          case 30: 
            { string.append('\r');
            }
          case 138: break;
          case 31: 
            { string.append('\n');
            }
          case 139: break;
          case 32: 
            { string.append('\"');
            }
          case 140: break;
          case 33: 
            { return symbol(Operators.SEMICOLON.value,yytext());
            }
          case 141: break;
          case 34: 
            { return symbol(ReservedWords.TRY.value,yytext());
            }
          case 142: break;
          case 35: 
            { return symbol(ReservedWords.REF.value,yytext());
            }
          case 143: break;
          case 36: 
            { return symbol(ReservedWords.OUT.value,yytext());
            }
          case 144: break;
          case 37: 
            { return symbol(ReservedWords.NEW.value,yytext());
            }
          case 145: break;
          case 38: 
            { return symbol(ReservedWords.INT.value,yytext());
            }
          case 146: break;
          case 39: 
            { return symbol(ReservedWords.FOR.value,yytext());
            }
          case 147: break;
          case 40: 
            { return symbol(ReservedWords.ARGS.value,yytext());
            }
          case 148: break;
          case 41: 
            { return symbol(ReservedWords.BASE.value,yytext());
            }
          case 149: break;
          case 42: 
            { return symbol(ReservedWords.BOOL.value,yytext());
            }
          case 150: break;
          case 43: 
            { return symbol(ReservedWords.BYTE.value,yytext());
            }
          case 151: break;
          case 44: 
            { return symbol(ReservedWords.TRUE.value,yytext());
            }
          case 152: break;
          case 45: 
            { return symbol(ReservedWords.THIS.value,yytext());
            }
          case 153: break;
          case 46: 
            { return symbol(ReservedWords.CASE.value,yytext());
            }
          case 154: break;
          case 47: 
            { return symbol(ReservedWords.CHAR.value,yytext());
            }
          case 155: break;
          case 48: 
            { return symbol(ReservedWords.ELSE.value,yytext());
            }
          case 156: break;
          case 49: 
            { return symbol(ReservedWords.ENUM.value,yytext());
            }
          case 157: break;
          case 50: 
            { return symbol(ReservedWords.LOCK.value,yytext());
            }
          case 158: break;
          case 51: 
            { return symbol(ReservedWords.LONG.value,yytext());
            }
          case 159: break;
          case 52: 
            { return symbol(ReservedWords.NULL.value,yytext());
            }
          case 160: break;
          case 53: 
            { return symbol(ReservedWords.UINT.value,yytext());
            }
          case 161: break;
          case 54: 
            { return symbol(ReservedWords.GOTO.value,yytext());
            }
          case 162: break;
          case 55: 
            { return symbol(ReservedWords.VOID.value,yytext());
            }
          case 163: break;
          case 56: 
            { return symbol(ReservedWords.MAIN.value,yytext());
            }
          case 164: break;
          case 57: 
            { return symbol(ReservedWords.BREAK.value,yytext());
            }
          case 165: break;
          case 58: 
            { return symbol(ReservedWords.SBYTE.value,yytext());
            }
          case 166: break;
          case 59: 
            { return symbol(ReservedWords.SHORT.value,yytext());
            }
          case 167: break;
          case 60: 
            { return symbol(ReservedWords.THROW.value,yytext());
            }
          case 168: break;
          case 61: 
            { return symbol(ReservedWords.CATCH.value,yytext());
            }
          case 169: break;
          case 62: 
            { return symbol(ReservedWords.CONST.value,yytext());
            }
          case 170: break;
          case 63: 
            { return symbol(ReservedWords.CLASS.value,yytext());
            }
          case 171: break;
          case 64: 
            { return symbol(ReservedWords.EVENT.value,yytext());
            }
          case 172: break;
          case 65: 
            { return symbol(ReservedWords.USING.value,yytext());
            }
          case 173: break;
          case 66: 
            { return symbol(ReservedWords.ULONG.value,yytext());
            }
          case 174: break;
          case 67: 
            { return symbol(ReservedWords.FALSE.value,yytext());
            }
          case 175: break;
          case 68: 
            { return symbol(ReservedWords.FLOAT.value,yytext());
            }
          case 176: break;
          case 69: 
            { return symbol(ReservedWords.FIXED.value,yytext());
            }
          case 177: break;
          case 70: 
            { return symbol(ReservedWords.WHILE.value,yytext());
            }
          case 178: break;
          case 71: 
            { return symbol(ReservedWords.STATIC.value,yytext());
            }
          case 179: break;
          case 72: 
            { return symbol(ReservedWords.STRING.value,yytext());
            }
          case 180: break;
          case 73: 
            { return symbol(ReservedWords.STRUCT.value,yytext());
            }
          case 181: break;
          case 74: 
            { return symbol(ReservedWords.SEALED.value,yytext());
            }
          case 182: break;
          case 75: 
            { return symbol(ReservedWords.SIZEOF.value,yytext());
            }
          case 183: break;
          case 76: 
            { return symbol(ReservedWords.SWITCH.value,yytext());
            }
          case 184: break;
          case 77: 
            { return symbol(ReservedWords.TYPEOF.value,yytext());
            }
          case 185: break;
          case 78: 
            { return symbol(ReservedWords.RETURN.value,yytext());
            }
          case 186: break;
          case 79: 
            { return symbol(ReservedWords.EXTERN.value,yytext());
            }
          case 187: break;
          case 80: 
            { return symbol(ReservedWords.OBJECT.value,yytext());
            }
          case 188: break;
          case 81: 
            { return symbol(ReservedWords.DOUBLE.value,yytext());
            }
          case 189: break;
          case 82: 
            { return symbol(ReservedWords.USHORT.value,yytext());
            }
          case 190: break;
          case 83: 
            { return symbol(ReservedWords.UNSAFE.value,yytext());
            }
          case 191: break;
          case 84: 
            { return symbol(ReservedWords.PARAMS.value,yytext());
            }
          case 192: break;
          case 85: 
            { return symbol(ReservedWords.PUBLIC.value,yytext());
            }
          case 193: break;
          case 86: 
            { return symbol(ReservedWords.CHECKED.value,yytext());
            }
          case 194: break;
          case 87: 
            { return symbol(ReservedWords.DECIMAL.value,yytext());
            }
          case 195: break;
          case 88: 
            { return symbol(ReservedWords.DEFAULT.value,yytext());
            }
          case 196: break;
          case 89: 
            { return symbol(ReservedWords.FOREACH.value,yytext());
            }
          case 197: break;
          case 90: 
            { return symbol(ReservedWords.FINALLY.value,yytext());
            }
          case 198: break;
          case 91: 
            { return symbol(ReservedWords.VIRTUAL.value,yytext());
            }
          case 199: break;
          case 92: 
            { return symbol(ReservedWords.PRIVATE.value,yytext());
            }
          case 200: break;
          case 93: 
            { return symbol(ReservedWords.ABSTRACT.value,yytext());
            }
          case 201: break;
          case 94: 
            { return symbol(ReservedWords.READONLY.value,yytext());
            }
          case 202: break;
          case 95: 
            { return symbol(ReservedWords.CONTINUE.value,yytext());
            }
          case 203: break;
          case 96: 
            { return symbol(ReservedWords.EXPLICIT.value,yytext());
            }
          case 204: break;
          case 97: 
            { return symbol(ReservedWords.OVERRIDE.value,yytext());
            }
          case 205: break;
          case 98: 
            { return symbol(ReservedWords.OPERATOR.value,yytext());
            }
          case 206: break;
          case 99: 
            { return symbol(ReservedWords.DELEGATE.value,yytext());
            }
          case 207: break;
          case 100: 
            { return symbol(ReservedWords.INTERNAL.value,yytext());
            }
          case 208: break;
          case 101: 
            { return symbol(ReservedWords.IMPLICIT.value,yytext());
            }
          case 209: break;
          case 102: 
            { return symbol(ReservedWords.READLINE.value,yytext());
            }
          case 210: break;
          case 103: 
            { return symbol(ReservedWords.NAMESPACE.value,yytext());
            }
          case 211: break;
          case 104: 
            { return symbol(ReservedWords.INTERFACE.value,yytext());
            }
          case 212: break;
          case 105: 
            { return symbol(ReservedWords.UNCHECKED.value,yytext());
            }
          case 213: break;
          case 106: 
            { return symbol(ReservedWords.PROTECTED.value,yytext());
            }
          case 214: break;
          case 107: 
            { return symbol(ReservedWords.WRITELINE.value,yytext());
            }
          case 215: break;
          case 108: 
            { return symbol(ReservedWords.STACKALLOC.value,yytext());
            }
          case 216: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
