/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package lexico;

/**
 *
 * @author Milton
 */
public enum ReservedWords {
      //ABSTRAC, AS, BASE, BOOL, BREAK, BYTE, CASE,CATCH,CHAR,CHECKED,CLASS,CONST,CONTINUE,DECIMAL,DEFAULT,DELEGATE,DO,DOUBLE,ELSE,ENUM,EVENT,EXPLICIT,EXTERN,FALSE,FINALLY,FIXED,FLOAT,FOR,FOREACH,GOTO,IF,IMPLICIT,IN,INT,INTERFACE,INTERNAL,IS,LOCK,LONG,NAMESPACE,NEW,NULL,OBJECT,OPERATOR,OUT,OVERRIDE,PARAMS,PRIVATE,PROTECTED,PUBLIC,READONLY,REF,RETURN,SBYTE,SEALED,SHORT,SIZEOF,STACKALLOC,STATIC,STRING,STRUCT,SWITCH, THIS, THROW, TRUE, TRY, TYPEOF,UINT, ULONG, UNCHECKED, UNSAFE,USHORT, USING,VIRTUAL,VOID, WHILE;
        
    ABSTRACT(1), AS(2), BASE(3), BOOL(4), BREAK(5), BYTE(6), CASE(7), 
    CATCH(8), CHAR(9), CHECKED(10), CLASS(11), CONST(12), CONTINUE(13), 
    DECIMAL(14), DEFAULT(15), DELEGATE(16), DO(17), DOUBLE(18), ELSE(19), 
    ENUM(20), EVENT(21), EXPLICIT(22), EXTERN(23), FALSE(24), FINALLY(25), 
    FLOAT(26), FOR(27), FOREACH(28), GOTO(29), IF(30), IMPLICIT(31), 
    IN(32), INT(33), INTERFACE(34), INTERNAL(35), IS(35), LOCK(37), LONG(38), 
    NAMESPACE(39), NEW(40), NULL(41), OBJECT(42), OPERATOR(43), OUT(44), OVERRIDE(45), 
    PARAMS(46), PRIVATE(47), PROTECTED(48), PUBLIC(49), READONLY(50), REF(51), RETURN(52), 
    SBYTE(53), SEALED(54), SHORT(55), SIZEOF(56), STACKALLOC(57), STATIC(58), STRING(59), 
    STRUCT(60), SWITCH(61), THIS(62), THROW(63), TRUE(64), TRY(65), TYPEOF(66), UINT(67), 
    ULONG(68), UNCHECKED(69), UNSAFE(70), USHORT(71), USING(72), VIRTUAL(73), VOID(74), 
    WHILE(75), STRING_LITERAL(76), INTEGER_LITERAL(77), SYSTEM(94), WRITELINE(95), 
    CONSOLE(96), WRITE(104), FIXED(105),READLINE(110),MAIN(111), ARGS(112);
    
    
    public int value;
    
    private ReservedWords(int value) {
        this.value = value;
    }
}
