
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package back;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 30;
  public static final int PARENTESIS_CIERRE = 22;
  public static final int CONST = 37;
  public static final int NAMESPACE = 43;
  public static final int CASE = 34;
  public static final int RESTA = 13;
  public static final int INTERFACE = 42;
  public static final int OPERADOR_BOOLEANO = 20;
  public static final int OUT = 45;
  public static final int OPERADOR_CONTEXTUAL = 57;
  public static final int FOR = 10;
  public static final int WRITE = 55;
  public static final int STATIC = 47;
  public static final int IDENTIFICADOR = 29;
  public static final int IGUAL = 11;
  public static final int CORCHETE_CIERRE = 26;
  public static final int OPERADOR_ATRIBUCION = 18;
  public static final int THROW = 49;
  public static final int CLASS = 36;
  public static final int SUMA = 12;
  public static final int MAIN = 27;
  public static final int IF = 6;
  public static final int PUNTO_COMA = 28;
  public static final int ABSTRACT = 32;
  public static final int EOF = 0;
  public static final int SYSTEM = 52;
  public static final int RETURN = 46;
  public static final int CORCHETE_APERTURA = 25;
  public static final int COMILLAS = 3;
  public static final int error = 1;
  public static final int CADENA = 5;
  public static final int TRY = 50;
  public static final int NULL = 44;
  public static final int TIPO_DATO = 4;
  public static final int BREAK = 33;
  public static final int VOID = 51;
  public static final int OPERADOR_LOGICO = 16;
  public static final int OPERADOR_INCREMENTO = 19;
  public static final int FINALLY = 39;
  public static final int ERROR = 31;
  public static final int SWITCH = 48;
  public static final int WRITELINE = 53;
  public static final int FOREACH = 40;
  public static final int OPERADOR_RELACIONAL = 17;
  public static final int ELSE = 7;
  public static final int LLAVE_APERTURA = 23;
  public static final int GOTO = 41;
  public static final int WHILE = 9;
  public static final int DEFAULT = 38;
  public static final int LLAVE_CIERRE = 24;
  public static final int PARENTESIS_APERTURA = 21;
  public static final int DIVISION = 15;
  public static final int LINEA = 2;
  public static final int CONSOLE = 54;
  public static final int DO = 8;
  public static final int MULTIPLICACION = 14;
  public static final int IDENTIFIER = 56;
  public static final int CATCH = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LINEA",
  "COMILLAS",
  "TIPO_DATO",
  "CADENA",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "IGUAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "OPERADOR_LOGICO",
  "OPERADOR_RELACIONAL",
  "OPERADOR_ATRIBUCION",
  "OPERADOR_INCREMENTO",
  "OPERADOR_BOOLEANO",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "LLAVE_APERTURA",
  "LLAVE_CIERRE",
  "CORCHETE_APERTURA",
  "CORCHETE_CIERRE",
  "MAIN",
  "PUNTO_COMA",
  "IDENTIFICADOR",
  "NUMERO",
  "ERROR",
  "ABSTRACT",
  "BREAK",
  "CASE",
  "CATCH",
  "CLASS",
  "CONST",
  "DEFAULT",
  "FINALLY",
  "FOREACH",
  "GOTO",
  "INTERFACE",
  "NAMESPACE",
  "NULL",
  "OUT",
  "RETURN",
  "STATIC",
  "SWITCH",
  "THROW",
  "TRY",
  "VOID",
  "SYSTEM",
  "WRITELINE",
  "CONSOLE",
  "WRITE",
  "IDENTIFIER",
  "OPERADOR_CONTEXTUAL"
  };
}

