/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;

/**
 *
 * @author Milton
 */
public class Editor extends javax.swing.JPanel {
    private File archivo;
    
    /**
     * Creates new form Editor
     */
    public Editor(File archivo) {
        this.archivo = archivo;
        if (!archivo.exists()) {
            try {
                if (!archivo.createNewFile()) {
                    JOptionPane.showMessageDialog(this, "No se pudo crear el archivo");
                } else {
                    initComponents();

                }
            } catch (IOException e) {
            }
        } else {
            initComponents();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaContenido = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        txaContenido.setColumns(20);
        txaContenido.setRows(5);
        jScrollPane1.setViewportView(txaContenido);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarContenido(){
    
    }

    public void guardar() throws FileNotFoundException, IOException{
            
            String str = txaContenido.getText();
            FileOutputStream outputStream = new FileOutputStream(this.archivo);
            byte[] strToBytes = str.getBytes();
            outputStream.write(strToBytes);
            

    outputStream.close();
    }
    
    public void abrir(File archivo) throws FileNotFoundException, IOException{
        
        //Variable que almacenara el resultado de la lectura del archivo
        String result;

        DataInputStream reader = new DataInputStream(new FileInputStream(archivo));
        int nBytesToRead = reader.available();
        if(nBytesToRead > 0) {
        byte[] bytes = new byte[nBytesToRead];
        reader.read(bytes);
        result = new String(bytes);
        txaContenido.append(result);
         
    }
        txaContenido.repaint();
    }
    
    public File getarchivo(){
    return archivo; 
            }
    
    public String getText(){
        return txaContenido.getText();
    }
    
    public void setText(String texto){
        txaContenido.append(texto);
        txaContenido.repaint();
    }
    
    public File getArchivo() {
        return archivo;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txaContenido;
    // End of variables declaration//GEN-END:variables

}
